/**
 * Resolves a ~1280px photo URL for every species from the Wikipedia REST API
 * and writes src/data/species/images.ts. Run once when species are added.
 * Sequential with retry to respect Wikipedia rate limits.
 */
import fs from "fs";
import path from "path";
import { allSpecies } from "../src/data/species";

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

function thumbAt(originalUrl: string, thumbUrl: string | undefined, origWidth: number, target = 1280): string {
  if (origWidth > 0 && origWidth <= target) return originalUrl;
  if (thumbUrl && thumbUrl.includes("/thumb/")) {
    return thumbUrl.replace(/\/\d+px-/, `/${target}px-`);
  }
  return originalUrl;
}

async function fetchSummary(title: string, attempt = 1): Promise<Record<string, unknown> | null> {
  const res = await fetch(
    `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title)}`,
    { headers: { "User-Agent": "ReelFishHelp/1.0 (image map generator)" } }
  );
  if (res.status === 429 && attempt <= 4) {
    await sleep(2000 * attempt);
    return fetchSummary(title, attempt + 1);
  }
  if (!res.ok) return null;
  return res.json();
}

async function main() {
  const entries: string[] = [];
  for (const s of allSpecies) {
    const d = (await fetchSummary(s.wikiTitle)) as {
      thumbnail?: { source: string };
      originalimage?: { source: string; width: number };
    } | null;
    const orig = d?.originalimage?.source;
    if (!orig) {
      console.log(`MISSING: ${s.slug} (${s.wikiTitle})`);
      continue;
    }
    const url = thumbAt(orig, d?.thumbnail?.source, d?.originalimage?.width ?? 0);
    entries.push(
      `  "${s.slug}": { url: ${JSON.stringify(url)}, credit: ${JSON.stringify(`Wikipedia — ${s.wikiTitle}`)} },`
    );
    console.log(`ok ${s.slug}`);
    await sleep(350);
  }

  const file = `/**
 * Pre-resolved species photo URLs (Wikipedia Commons, ~1280px thumbnails).
 * Generated by scripts/generate-image-map.ts — regenerate after adding species.
 */
export const speciesImages: Record<string, { url: string; credit: string }> = {
${entries.join("\n")}
};
`;
  fs.writeFileSync(path.join(process.cwd(), "src", "data", "species", "images.ts"), file);
  console.log(`\nwrote images.ts with ${entries.length}/${allSpecies.length} entries`);
}

main();
